# Generated by Django 5.1.3 on 2024-11-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("mse", models.FloatField()),
                ("r2_score", models.FloatField()),
                ("cross_val_r2_mean", models.FloatField()),
                ("cross_val_r2_std", models.FloatField()),
                ("accuracy_within_tolerance", models.FloatField(blank=True, null=True)),
                ("trained_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
